### ISSUE TITLE
design thoughts

### ISSUE THREAD

**Issue by jbjonesjr** [jbjonesjr/atom-task#2]
Have a right pane (similar to the left pane tree viewer) that lists tasks (using typical markdown task syntax I guess...)

Would also be nice if it could support titles (##? ###?) for groupings.

Bonus for some sort of calendar date notation as well.

Example:

===================

### Tasks for Tuesday ###
- [ ] Do some stuff
- [ ] Give a Vanilla Demo
- [ ] Talk to epem

### Tasks for atom-tasks ###
- [ ] Spike out details
- [ ] Figure out how to really do panes
- [ ] figure out how to use the markdown renderer for the pane ([markdown preview](https://github.com/atom/markdown-preview) as an example?)
- [ ] bonus points if we can have a form to build the task list vs a markdown doc

========================
